### ISSUE TITLE
Clear error message for undefined variable in Watchers

### ISSUE THREAD

**Issue by ktisha** [sproshev/TheRPlugin#18]
Value for undefined variable is empty:

![undefined_variable](https://cloud.githubusercontent.com/assets/437080/8678857/b6467d60-2a5f-11e5-977c-7e8ab1654989.png)

In Java:
![undefined_variable_java](https://cloud.githubusercontent.com/assets/437080/8678818/7e429ad4-2a5f-11e5-9a20-4acf8a83ed07.png)

**Comment by sproshev** [comment]
Fixed in [e416af900242618ee724fc3f7d8b4c00b844b73d, .., 407c7740e2549535d26fd62e27eda05432c3a6b8]
