### ISSUE TITLE
Step to the next line doesn't work if breakpoint is on the for statement

### ISSUE THREAD

**Issue by ktisha** [sproshev/TheRPlugin#36]
packageNames <- .packages(all = TRUE)

for (name in packageNames) {
    shouldLoadLibrary = FALSE
}

**Comment by sproshev** [comment]
The reason of this bug is described [here](https://github.com/sproshev/TheRPlugin/issues/37#issuecomment-136421717).

**Comment by sproshev** [comment]
Fixed in af94477fc9645db592754fd0044a466a5ab2995d.
